baseURL = "https://dockingbay.info/"
languageCode = "en-us"
title = "Docking Bay"
author = "Shawn Medero"
copyright = "Â© dockingbay.info 2026"
theme = ["hugo-bearblog"]

enableRobotsTXT = true

summaryLength = 50

[taxonomies]
  game = 'games'
  series = 'series'
  universe = 'universes'
  tag = 'tags'

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[permalinks]
	blog = "/blog/:slug/"
	tags = "/tags/:slug"

[params]
	description = "Sci-Fi Solitaire RPG adventures"
	title = "dockingbay.info"
	hideMadeWithLine = true
	enablePostNavigator = true
	
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true